use_frameworks!

platform :ios, '10.0'

target 'GMSLibrary_Example' do
  pod 'GMSLibrary', :path => '../'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'GMSLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
